SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3 # sizes 20, 40, 60. want anymore?
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PADDING = 100 # number of pixels

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 450 # mine
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
SHOT_DISTANCE = 500
