SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 10
ASTEROID_KINDS = 3 # sizes 20, 40, 60. want more?
#ASTEROID_SPAWN_RATE = 2.0  # formerly 0.8 seconds // No longer used, see asteroid_field.py
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PADDING = 100 # number of pixels

UPGRADE_RADIUS = 15

ASTEROID_HOMING_RANGE = 500
ASTEROID_HOMING_SPEED = 80

PLAYER_RADIUS = 10

PLAYER_TURN_SPEED = 450
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.5

SHOT_RADIUS = 3
SHOT_DISTANCE = 1000

HIGH_SCORE_FILE = "highscore.txt"